[package]
name = "index"
version = "1.0.0"
authors = ["Your Name <your@site.com>"]
edition = "2018"

[dependencies]
horrorshow = "0.8.4"
http = "0.1"
vercel_lambda = "*"

[lib]
name = "util"
path = "_util.rs"
